### ISSUE TITLE
MINGW64 blockchain-wallet-service Throws Javascript and Error

### ISSUE THREAD

**Issue by GoldFund** [blockchain/My-Wallet-V3#542]
Hi, occasionally The blockchain-wallet-service (version 0.26.1 ) throws an error and fills the terminal window with javascript.

Also it provides an error message (not all the time)

I have copied below. Please let me know if I need to upgrade or change some API call process.

Thanks

1539393629753 - error: ERR_SYNC

<script type="text/javascript">
//<![CDATA[
!function(){function e(e,t){return[].slice.call((t||document).querySelectorAll(e))}if(window.addEventListener){var t=window.StyleFix={link:function(e){try{if("stylesheet"!==e.rel||e.hasAttribute("data-noprefix"))return}catch(r){return}var n,i=e.href||e.getAttribute("data-href"),a=i.replace(/[^\/]+$/,""),o=(/^[a-z]{3,10}:/.exec(a)||[""])[0],s=(/^[a-z]{3,10}:\/\/[^\/]+/.exec(a)||[""])[0],l=/^([^?]*)\??/.exec(i)[1],u=e.parentNode,p=new XMLHttpRequest;p.onreadystatechange=function(){4===p.readyState&&n()},n=function(){var r=p.responseText;if(r&&e.parentNode&&(!p.status||400>p.status||600<p.status)){if(r=t.fix(r,!0,e),a)var r=r.replace(/url\(\s*?((?:"|')?)(.+?)\1\s*?\)/gi,function(e,t,r){return/^([a-z]{3,10}:|#)/i.test(r)?e:/^\/\//.test(r)?'url("'+o+r+'")':/^\//.test(r)?'url("'+s+r+'")':/^\?/.test(r)?'url("'+l+r+'")':'url("'+a+r+'")'}),n=a.replace(/([\\\^\$*+[\]?{}.=!:(|)])/g,"\\$1"),r=r.replace(RegExp("\\b(behavior:\\s*?url\\('?\"?)"+n,"gi"),"$1");n=document.createElement("style"),n.textContent=r,n.media=e.media,n.disabled=e.disabled,n.setAttribute("data-href",e.getAttribute("href")),u.insertBefore(n,e),u.removeChild(e),n.media=e.media}};try{p.open("GET",i),p.send(null)}catch(f){"undefined"!=typeof XDomainRequest&&(p=new XDomainRequest,p.onerror=p.onprogress=function(){},p.onload=n,p.open("GET",i),p.send(null))}e.setAttribute("data-inprogress","")},styleElement:function(e){if(!e.hasAttribute("data-noprefix")){var r=e.disabled;e.textContent=t.fix(e.textContent,!0,e),e.disabled=r}},styleAttribute:function(e){var r=e.getAttribute("style"),r=t.fix(r,!1,e);e.setAttribute("style",r)},process:function(){e('link[rel="stylesheet"]:not([data-inprogress])').forEach(StyleFix.link),e("style").forEach(StyleFix.styleElement),e("[style]").forEach(StyleFix.styleAttribute)},register:function(e,r){(t.fixers=t.fixers||[]).splice(void 0===r?t.fixers.length:r,0,e)},fix:function(e,r,n){for(var i=0;i<t.fixers.length;i++)e=t.fixers[i](e,r,n)||e;return e},camelCase:function(e){return e.replace(/-([a-z])/g,function(e,t){return t.toUpperCase()}).replace("-","")},deCamelCase:function(e){return e.replace(/[A-Z]/g,function(e){return"-"+e.toLowerCase()})}};!function(){setTimeout(function(){e('link[rel="stylesheet"]').forEach(StyleFix.link)},10),document.addEventListener("DOMContentLoaded",StyleFix.process,!1)}()}}(),function(e){function t(e,t,n,i,a){return e=r[e],e.length&&(e=RegExp(t+"("+e.join("|")+")"+n,"gi"),a=a.replace(e,i)),a}if(window.StyleFix&&window.getComputedStyle){var r=window.PrefixFree={prefixCSS:function(e,n,i){var a=r.prefix;if(-1<r.functions.indexOf("linear-gradient")&&(e=e.replace(/(\s|:|,)(repeating-)?linear-gradient\(\s*(-?\d*\.?\d*)deg/gi,function(e,t,r,n){return t+(r||"")+"linear-gradient("+(90-n)+"deg"})),e=t("functions","(\\s|:|,)","\\s*\\(","$1"+a+"$2(",e),e=t("keywords","(\\s|:)","(\\s|;|\\}|$)","$1"+a+"$2$3",e),e=t("properties","(^|\\{|\\s|;)","\\s*:","$1"+a+"$2:",e),r.properties.length){var o=RegExp("\\b("+r.properties.join("|")+")(?!:)","gi");e=t("valueProperties","\\b",":(.+?);",function(e){return e.replace(o,a+"$1")},e)}return n&&(e=t("selectors","","\\b",r.prefixSelector,e),e=t("atrules","@","\\b","@"+a+"$1",e)),e=e.replace(RegExp("-"+a,"g"),"-"),e=e.replace(/-\*-(?=[a-z]+)/gi,r.prefix)},property:function(e){return(0<=r.properties.indexOf(e)?r.prefix:"")+e},value:function(e,n){return e=t("functions","(^|\\s|,)","\\s*\\(","$1"+r.prefix+"$2(",e),e=t("keywords","(^|\\s)","(\\s|$)","$1"+r.prefix+"$2$3",e),0<=r.valueProperties.indexOf(n)&&(e=t("properties","(^|\\s|,)","($|\\s|,)","$1"+r.prefix+"$2$3",e)),e},prefixSelector:function(e){return e.replace(/^:{1,2}/,function(e){return e+r.prefix})},prefixProperty:function(e,t){var n=r.prefix+e;return t?StyleFix.camelCase(n):n}};!function(){var e={},t=[],n=getComputedStyle(document.documentElement,null),i=document.createElement("div").style,a=function(r){if("-"===r.charAt(0)){t.push(r),r=r.split("-");var n=r[1];for(e[n]=++e[n]||1;3<r.length;)r.pop(),n=r.join("-"),StyleFix.camelCase(n)in i&&-1===t.indexOf(n)&&t.push(n)}};if(0<n.length)for(var o=0;o<n.length;o++)a(n[o]);else for(var s in n)a(StyleFix.deCamelCase(s));var l,u,o=0;for(u in e)n=e[u],n>o&&(l=u,o=n);for(r.prefix="-"+l+"-",r.Prefix=StyleFix.camelCase(r.prefix),r.properties=[],o=0;o<t.length;o++)s=t[o],0===s.indexOf(r.prefix)&&(l=s.slice(r.prefix.length),StyleFix.camelCase(l)in i||r.properties.push(l));!("Ms"!=r.Prefix||"transform"in i||"MsTransform"in i)&&"msTransform"in i&&r.properties.push("transform","transform-origin"),r.properties.sort()}(),function(){function e(e,t){return a[t]="",a[t]=e,!!a[t]}var t={"linear-gradient":{property:"backgroundImage",params:"red, teal"},calc:{property:"width",params:"1px + 5%"},element:{property:"backgroundImage",params:"#foo"},"cross-fade":{property:"backgroundImage",params:"url(a.png), url(b.png), 50%"}};t["repeating-linear-gradient"]=t["repeating-radial-gradient"]=t["radial-gradient"]=t["linear-gradient"];var n={initial:"color","zoom-in":"cursor","zoom-out":"cursor",box:"display",flexbox:"display","inline-flexbox":"display",flex:"display","inline-flex":"display",grid:"display","inline-grid":"display","max-content":"width","min-content":"width","fit-content":"width","fill-available":"width"};r.functions=[],r.keywords=[];var i,a=document.createElement("div").style;for(i in t){var o=t[i],s=o.property,o=i+"("+o.params+")";!e(o,s)&&e(r.prefix+o,s)&&r.functions.push(i)}for(var l in n)s=n[l],!e(l,s)&&e(r.prefix+l,s)&&r.keywords.push(l)}(),function(){function t(e){return o.textContent=e+"{}",!!o.sheet.cssRules.length}var n={":read-only":null,":read-write":null,":any-link":null,"::selection":null},i={keyframes:"name",viewport:null,document:'regexp(".")'};r.selectors=[],r.atrules=[];var a,o=e.appendChild(document.createElement("style"));for(a in n){var s=a+(n[a]?"("+n[a]+")":"");!t(s)&&t(r.prefixSelector(s))&&r.selectors.push(a)}for(var l in i)s=l+" "+(i[l]||""),!t("@"+s)&&t("@"+r.prefix+s)&&r.atrules.push(l);e.removeChild(o)}(),r.valueProperties=["transition","transition-property"],e.className+=" "+r.prefix,StyleFix.register(r.prefixCSS)}}(document.documentElement);
//]]>
</script>

Also, further to these errors, this one.

$ blockchain-wallet-service start --port 3030
1539396625504 - info: blockchain.info wallet service v0.26.1 running on http://127.0.0.1:3030
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:20)
    at fetchSuccess (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by GoldFund** [comment]
Seems that it is happening a lot. I am having difficulty creating wallet accounts now. This is the error.
$ blockchain-wallet-service start --port 3030
1539487288380 - info: blockchain.info wallet service v0.26.1 running on http://127.0.0.1:3030
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:20)
    at fetchSuccess (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by 1Bennell** [comment]
Is this where I receive my payment

**Comment by GoldFund** [comment]
> Is this where I receive my payment

Hi, I do not know what you are talking about. This issue I raised is regarding the failure of the API to create wallet accounts. Nothing to do with payments. The API is functioning perfectly for transfer, and balances etc, it's just the wallet account creation process that is failing for me. regs TIM
